CREATE TABLE IF NOT EXISTS events (day TEXT NOT NULL, name TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (day, name, detail));

CREATE INDEX IF NOT EXISTS events_day_idx ON events (day);
